---
apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: dist-mnist-kube
  namespace: mykubey
spec:
  replicaSpecs:
  - replicas: 3
    template:
      spec:
        containers:
        - args:
          - python
          - /opt/mnist_replica.py
          image: docker.io/raddaoui/tfjob_mnist_image:2.0
          name: tensorflow
        restartPolicy: OnFailure
    tfReplicaType: WORKER
  - replicas: 2
    template:
      spec:
        containers:
        - args:
          - python
          - /opt/mnist_replica.py
          image: docker.io/raddaoui/tfjob_mnist_image:2.0
          name: tensorflow
        restartPolicy: OnFailure
    tfReplicaType: PS
  terminationPolicy:
    chief:
      replicaIndex: 0
      replicaName: WORKER